#!/usr/bin/env bash
#Install nginx on a server and start it
sudo apt update
sudo apt install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "<body>
    Hello World!
</body>" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
