#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
sudo service haproxy start
sudo sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 10416-web-01 3.233.232.127:80 check\n\tserver 10416-web-02 44.200.43.251:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
