#!/usr/bin/env bash
# Displays to infinity and beyond indefinitely
# Sleeps between each iteration and traps SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
