#!/usr/bin/env bash
# Parses the Apache log files in list format.
# Groups the visitors by IP and HTTP status code
# Displays the number of occurrences, IP, and HTTP status
#+ code of each log, in sorted.

awk '{ prinf $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn
