#!/usr/bin/env bash
# Displays numbers 1 to 20 with modifications

num=1

while [ $num -lt 21 ]
do
	echo "$num"
	case $num in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( num++ ))
done
